name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main  # Adjust branch as needed
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🚚 Install dependencies
      run: npm install

    - name: Set up SMTP environment variables
      run: |
        echo "SMTP_HOST=${{ secrets.MAIL_HOST }}" >> .env.local
        echo "SMTP_PORT=${{ secrets.MAIL_PORT }}" >> .env.local
        echo "SMTP_USERNAME=${{ secrets.MAIL_USER }}" >> .env.local
        echo "SMTP_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env.local

    - name: 🔨 Build and export the Project
      run: |
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASSWORD }}
        local-dir: out/
        server-dir: /htdocs/

